/*
 * Shared audio event model contract.
 */

#ifndef __APPS_EXAMPLES_AUDIO_EVENT_AUDIO_EVENT_CONFIG_H
#define __APPS_EXAMPLES_AUDIO_EVENT_AUDIO_EVENT_CONFIG_H

#define AUDIO_EVENT_SAMPLE_RATE          16000
#define AUDIO_EVENT_CLIP_SAMPLES         16000
#define AUDIO_EVENT_WINDOW_SAMPLES       480
#define AUDIO_EVENT_WINDOW_STEP_SAMPLES  320
#define AUDIO_EVENT_FFT_SIZE              512
#define AUDIO_EVENT_FEATURE_FRAMES         49
#define AUDIO_EVENT_FEATURE_BINS           40
#define AUDIO_EVENT_FEATURE_CHANNELS        3
#define AUDIO_EVENT_FEATURE_PLANE_SIZE   1960
#define AUDIO_EVENT_FEATURE_SIZE         5880
#define AUDIO_EVENT_CLASS_COUNT             4

enum audio_event_class_e
{
  AUDIO_EVENT_CLASS_KNOCK = 0,
  AUDIO_EVENT_CLASS_COUGH,
  AUDIO_EVENT_CLASS_BACKGROUND,
  AUDIO_EVENT_CLASS_SILENCE
};

#endif /* __APPS_EXAMPLES_AUDIO_EVENT_AUDIO_EVENT_CONFIG_H */
